name: CI/CD_demo
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.1
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.1
    - name: Install dependencies
      run: |
        make install
    - name: Test
      run: |
        make test